name: rust-db-adapter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy




  test:
    name: Run tests
    runs-on: ubuntu-latest
    container: rust:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: botanist
          POSTGRES_PASSWORD: botanist
          POSTGRES_DB: botanist
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set .env file
        run: |
          echo "TEST_DB_URL="postgres://botanist:botanist@postgres:5432/"" >> .env
          echo "DATABASE_URL="postgres://botanist:botanist@postgres:5432/botanist"" >> .env
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli
      - name: Apply migrations
        run: sqlx migrate run

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads=1